// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description of product 1",
                            Name = "Product 1",
                            Price = 960m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description of product 2",
                            Name = "Product 2",
                            Price = 286m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description of product 3",
                            Name = "Product 3",
                            Price = 190m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description of product 4",
                            Name = "Product 4",
                            Price = 950m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description of product 5",
                            Name = "Product 5",
                            Price = 631m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description of product 6",
                            Name = "Product 6",
                            Price = 841m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description of product 7",
                            Name = "Product 7",
                            Price = 605m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description of product 8",
                            Name = "Product 8",
                            Price = 435m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description of product 9",
                            Name = "Product 9",
                            Price = 110m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description of product 10",
                            Name = "Product 10",
                            Price = 439m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description of product 11",
                            Name = "Product 11",
                            Price = 109m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description of product 12",
                            Name = "Product 12",
                            Price = 904m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description of product 13",
                            Name = "Product 13",
                            Price = 983m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description of product 14",
                            Name = "Product 14",
                            Price = 644m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description of product 15",
                            Name = "Product 15",
                            Price = 900m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description of product 16",
                            Name = "Product 16",
                            Price = 952m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description of product 17",
                            Name = "Product 17",
                            Price = 746m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description of product 18",
                            Name = "Product 18",
                            Price = 142m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description of product 19",
                            Name = "Product 19",
                            Price = 843m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description of product 20",
                            Name = "Product 20",
                            Price = 813m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description of product 21",
                            Name = "Product 21",
                            Price = 857m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description of product 22",
                            Name = "Product 22",
                            Price = 630m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description of product 23",
                            Name = "Product 23",
                            Price = 393m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description of product 24",
                            Name = "Product 24",
                            Price = 669m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description of product 25",
                            Name = "Product 25",
                            Price = 974m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description of product 26",
                            Name = "Product 26",
                            Price = 589m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description of product 27",
                            Name = "Product 27",
                            Price = 425m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description of product 28",
                            Name = "Product 28",
                            Price = 975m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description of product 29",
                            Name = "Product 29",
                            Price = 154m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description of product 30",
                            Name = "Product 30",
                            Price = 697m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description of product 31",
                            Name = "Product 31",
                            Price = 182m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description of product 32",
                            Name = "Product 32",
                            Price = 422m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description of product 33",
                            Name = "Product 33",
                            Price = 882m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description of product 34",
                            Name = "Product 34",
                            Price = 867m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description of product 35",
                            Name = "Product 35",
                            Price = 758m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description of product 36",
                            Name = "Product 36",
                            Price = 129m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description of product 37",
                            Name = "Product 37",
                            Price = 829m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description of product 38",
                            Name = "Product 38",
                            Price = 502m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description of product 39",
                            Name = "Product 39",
                            Price = 899m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description of product 40",
                            Name = "Product 40",
                            Price = 727m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description of product 41",
                            Name = "Product 41",
                            Price = 645m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description of product 42",
                            Name = "Product 42",
                            Price = 831m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description of product 43",
                            Name = "Product 43",
                            Price = 714m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description of product 44",
                            Name = "Product 44",
                            Price = 161m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description of product 45",
                            Name = "Product 45",
                            Price = 125m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description of product 46",
                            Name = "Product 46",
                            Price = 454m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description of product 47",
                            Name = "Product 47",
                            Price = 800m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description of product 48",
                            Name = "Product 48",
                            Price = 367m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description of product 49",
                            Name = "Product 49",
                            Price = 641m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description of product 50",
                            Name = "Product 50",
                            Price = 436m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description of product 51",
                            Name = "Product 51",
                            Price = 737m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description of product 52",
                            Name = "Product 52",
                            Price = 103m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description of product 53",
                            Name = "Product 53",
                            Price = 664m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description of product 54",
                            Name = "Product 54",
                            Price = 376m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description of product 55",
                            Name = "Product 55",
                            Price = 945m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description of product 56",
                            Name = "Product 56",
                            Price = 430m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description of product 57",
                            Name = "Product 57",
                            Price = 892m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description of product 58",
                            Name = "Product 58",
                            Price = 520m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description of product 59",
                            Name = "Product 59",
                            Price = 975m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description of product 60",
                            Name = "Product 60",
                            Price = 141m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description of product 61",
                            Name = "Product 61",
                            Price = 515m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description of product 62",
                            Name = "Product 62",
                            Price = 630m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description of product 63",
                            Name = "Product 63",
                            Price = 380m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description of product 64",
                            Name = "Product 64",
                            Price = 413m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description of product 65",
                            Name = "Product 65",
                            Price = 356m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description of product 66",
                            Name = "Product 66",
                            Price = 686m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description of product 67",
                            Name = "Product 67",
                            Price = 121m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description of product 68",
                            Name = "Product 68",
                            Price = 216m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description of product 69",
                            Name = "Product 69",
                            Price = 885m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description of product 70",
                            Name = "Product 70",
                            Price = 871m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description of product 71",
                            Name = "Product 71",
                            Price = 223m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description of product 72",
                            Name = "Product 72",
                            Price = 344m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description of product 73",
                            Name = "Product 73",
                            Price = 243m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description of product 74",
                            Name = "Product 74",
                            Price = 215m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description of product 75",
                            Name = "Product 75",
                            Price = 268m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description of product 76",
                            Name = "Product 76",
                            Price = 125m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description of product 77",
                            Name = "Product 77",
                            Price = 915m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description of product 78",
                            Name = "Product 78",
                            Price = 332m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description of product 79",
                            Name = "Product 79",
                            Price = 644m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description of product 80",
                            Name = "Product 80",
                            Price = 619m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description of product 81",
                            Name = "Product 81",
                            Price = 788m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description of product 82",
                            Name = "Product 82",
                            Price = 157m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description of product 83",
                            Name = "Product 83",
                            Price = 433m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description of product 84",
                            Name = "Product 84",
                            Price = 718m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description of product 85",
                            Name = "Product 85",
                            Price = 960m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description of product 86",
                            Name = "Product 86",
                            Price = 179m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description of product 87",
                            Name = "Product 87",
                            Price = 757m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description of product 88",
                            Name = "Product 88",
                            Price = 606m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description of product 89",
                            Name = "Product 89",
                            Price = 921m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description of product 90",
                            Name = "Product 90",
                            Price = 428m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description of product 91",
                            Name = "Product 91",
                            Price = 237m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description of product 92",
                            Name = "Product 92",
                            Price = 409m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description of product 93",
                            Name = "Product 93",
                            Price = 527m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description of product 94",
                            Name = "Product 94",
                            Price = 857m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description of product 95",
                            Name = "Product 95",
                            Price = 311m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description of product 96",
                            Name = "Product 96",
                            Price = 115m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description of product 97",
                            Name = "Product 97",
                            Price = 551m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description of product 98",
                            Name = "Product 98",
                            Price = 401m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description of product 99",
                            Name = "Product 99",
                            Price = 805m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description of product 100",
                            Name = "Product 100",
                            Price = 438m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 47
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 94
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 47
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 62
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 94
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 99
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 61
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
